//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSD
    {
        public int ID { get; set; }
        public string IDSIM { get; set; }
        public System.DateTime TGBD { get; set; }
        public System.DateTime TGKT { get; set; }
        public Nullable<double> SOPHUTSD { get; set; }
        public Nullable<decimal> CUOCPHI { get; set; }
    
        public virtual THONGTINSIM THONGTINSIM { get; set; }
    }
}
