//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDDK
    {
        public int ID { get; set; }
        public string IDSIM { get; set; }
        public int IDKH { get; set; }
        public decimal CUOCDK { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual THONGTINSIM THONGTINSIM { get; set; }
    }
}
