//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCDT
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CHITIETSD
    {
        [DisplayName("Mã cuộc gọi")]
        public int ID { get; set; }
        [DisplayName("SIM")]
        public string IDSIM { get; set; }
        [DisplayName("Từ")]
        public System.DateTime TGBD { get; set; }
        [DisplayName("Đến")]
        public System.DateTime TGKT { get; set; }
        [DisplayName("Số phút")]
        public Nullable<double> SOPHUTSD { get; set; }
        [DisplayName("Cước phí")]
        public Nullable<decimal> CUOCPHI { get; set; }

        [Browsable(false)]
        public virtual THONGTINSIM THONGTINSIM { get; set; }

    }
}
