//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCDT
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class GIACUOC
    {
        [Browsable(false)]
        public int ID { get; set; }
        [DisplayName("Từ")]
        public System.TimeSpan TGBD { get; set; }
        [DisplayName("Đến")]
        public System.TimeSpan TGKT { get; set; }
        [DisplayName("Giá cước")]
        public Nullable<decimal> GIACUOC1 { get; set; }
    }
}
