//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCDT
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HDTC
    {
        [DisplayName("Mã thanh toán")]
        public int ID { get; set; }
        [DisplayName("SIM")]
        public string IDSIM { get; set; }
        [DisplayName("Khách hàng")]
        public virtual KHACHHANG KHACHHANG { get; set; }
        [Browsable(false)]
        public int IDKH { get; set; }
        [DisplayName("Tháng")]
        public Nullable<int> THANG { get; set; }
        [DisplayName("Năm")]
        public Nullable<int> NAM { get; set; }
        [DisplayName("Số tiền")]
        public decimal TONGTIEN { get; set; }
        [Browsable(false)]
        public bool THANHTOAN { get; set; }
        [DisplayName("Trạng thái")]
        public string ThanhToan
        {
            get
            {
                return THANHTOAN ? "Đã thanh toán" : "Chưa thanh toán";
            }
            set
            {
                THANHTOAN = (value == "Đã thanh toán");
            }
        }

        [Browsable(false)]
        public virtual THONGTINSIM THONGTINSIM { get; set; }

    }
}
