//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCDT
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HDDKs = new HashSet<HDDK>();
            this.HDTCs = new HashSet<HDTC>();
        }

        [DisplayName("Mã khách hàng")]
        public int ID { get; set; }
        [DisplayName("Tên khách hàng")]
        public string TENKH { get; set; }
        [DisplayName("Email")]
        public string EMAIL { get; set; }
        [DisplayName("CMND")]
        public string CMND { get; set; }
        [DisplayName("Nghề nghiệp")]
        public string NGHENGHIEP { get; set; }
        [DisplayName("Chức vụ")]
        public string CHUCVU { get; set; }
        [DisplayName("Địa chỉ")]
        public string DIACHI { get; set; }
        [Browsable(false)]
        public Nullable<bool> TINHTRANG { get; set; }

        [Browsable(false)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDDK> HDDKs { get; set; }
        [Browsable(false)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDTC> HDTCs { get; set; }

        public override string ToString()
        {
            return TENKH;
        }
    
    }
}
