CREATE FUNCTION CUOCPHUT(@THOIGIAN DATETIME, @BD BIT = 1)
RETURNS DECIMAL
AS
BEGIN
	DECLARE @Time TIME = CAST(@ThoiGian AS TIME)
	DECLARE @Zero TIME = '00:00'
	DECLARE @Max TIME = '23:59'
	DECLARE @Cuoc DECIMAL = (
		SELECT GIACUOC
		FROM GIACUOC
		WHERE (TGBD < TGKT AND TGBD <= @Time AND @Time < TGKT) OR
			  (TGBD > TGKT AND (TGBD <= @Time AND @Time <= @MAX OR @Zero <= @Time AND @Time < TGKT) )
	)
	DECLARE @SoGiay DECIMAL
	IF @BD = 1 SET @SoGiay = 60 - DATEPART(SECOND, @THOIGIAN)
	ELSE SET @SoGiay = DATEPART(SECOND, @THOIGIAN)
	RETURN (@SoGiay / 60.0) * @Cuoc
END
