CREATE FUNCTION TINHCUOC(@TGBD DATETIME, @TGKT DATETIME)
RETURNS DECIMAL
AS
BEGIN
	IF DATEADD(SECOND, -DATEPART(SECOND, @TGBD), @TGBD) = DATEADD(SECOND, -DATEPART(SECOND, @TGKT), @TGKT)
		RETURN dbo.CUOCPHUT(@TGKT, 0) - dbo.CUOCPHUT(@TGBD, 0)

	DECLARE @Start DATETIME = DATEADD(SECOND, 60 - DATEPART(SECOND, @TGBD), @TGBD)
	DECLARE @End DATETIME = DATEADD(SECOND, -DATEPART(SECOND, @TGKT), @TGKT)

	DECLARE @MidCost DECIMAL = 0.0
	WHILE @Start <= @End
	BEGIN
		SET @MidCost = @MidCost + dbo.CUOCPHUT(@Start, 1)
		SET @Start = DATEADD(MINUTE, 1, @Start)
	END

	RETURN dbo.CUOCPHUT(@TGBD, 1) + @MidCost + dbo.CUOCPHUT(@TGKT, 0)
END
